stages:
  - name: Compile And Test
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: ${CICD_GIT_REPO_NAME}/next:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./configMaps/global.yaml
      - applyYamlConfig:
          path: ./k8s/deployment-dev.yaml
        when:
          branch:
            include:
              - develop
      - applyYamlConfig:
          path: ./configMaps/config-dev.yaml
        when:
          branch:
            include:
              - develop
      - applyYamlConfig:
          path: ./k8s/deployment-pre.yaml
        when:
          branch:
            include:
              - release/*
      - applyYamlConfig:
          path: ./configMaps/config-pre.yaml
        when:
          branch:
            include:
              - release/*
      - applyYamlConfig:
          path: ./k8s/deployment-prod.yaml
        when:
          branch:
            include:
              - master
      - applyYamlConfig:
          path: ./configMaps/config-prod.yaml
        when:
          branch:
            include:
              - master
timeout: 10
branch:
  include:
    - master
    - develop
    - release/*
notification: {}
